/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppointmentStatus } from '../models/appointment-status';
import { EntityModel } from '../models/entity-model';
import { PatientModel } from '../models/patient-model';
import { PrescriptionModel } from '../models/prescription-model';
export type AppointmentModel = EntityModel & {
'dateTime': string;
'reason'?: string | null;
'status': AppointmentStatus;
'patientId': number;
'patient'?: PatientModel | null;
'doctorId': number;
'doctorName'?: string | null;
'notes'?: string | null;
'prescriptions'?: Array<PrescriptionModel> | null;
};
