/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppointmentStatus } from '../models/appointment-status';
import { Doctor } from '../models/doctor';
import { Entity } from '../models/entity';
import { Prescription } from '../models/prescription';
import { User } from '../models/user';
export type Appointment = Entity & {
'dateTime'?: string;
'reason'?: string | null;
'status'?: AppointmentStatus;
'notes'?: Array<string> | null;
'patientId'?: number;
'patient'?: User | null;
'doctorId'?: number;
'doctor'?: Doctor | null;
'prescriptions'?: Array<Prescription> | null;
};
