/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppointmentStatus } from '../models/appointment-status';
import { EntityModel } from '../models/entity-model';
export type AppointmentModel = EntityModel & {
'dateTime'?: string;
'reason'?: string | null;
'status'?: AppointmentStatus;
'patientId'?: number;
'doctorId'?: number;
};
