/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAppointmentModel {
  dateTime: string;
  doctorId: number;
  patientId?: number;
  reason?: string | null;
}
