/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDoctorModel {
  departmentId?: number;
  email: string;
  firstName: string;
  hospitalId?: number;
  lastName: string;
  password: string;
  username: string;
}
