/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RegisterUserRequestModel } from '../models/register-user-request-model';
export type CreateDoctorModel = RegisterUserRequestModel & {
'hospitalId'?: number;
'departmentId'?: number;
};
