/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Appointment } from '../models/appointment';
import { Department } from '../models/department';
import { Entity } from '../models/entity';
import { Hospital } from '../models/hospital';
import { User } from '../models/user';
export type Doctor = Entity & {
'userId': number;
'user'?: User | null;
'hospitalId': number;
'hospital'?: Hospital | null;
'departmentId': number;
'department'?: Department | null;
'appointments'?: Array<Appointment> | null;
};
