/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DoctorModel {
  createdBy?: string | null;
  createdOn?: string;
  departmentId: number;
  departmentName?: string | null;
  firstName?: string | null;
  hospitalId: number;
  hospitalName?: string | null;
  id?: number;
  lastName?: string | null;
  modifiedBy?: string | null;
  modifiedOn?: string;
  userId: number;
}
