/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Department } from '../models/department';
import { Hospital } from '../models/hospital';
import { User } from '../models/user';
export interface Doctor {
  createdBy?: string | null;
  createdOn?: string;
  department?: Department;
  departmentId: number;
  hospital?: Hospital;
  hospitalId: number;
  id?: number;
  modifiedBy?: string | null;
  modifiedOn?: string;
  user?: User;
  userId: number;
}
