/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EntityModel {
  createdBy?: string | null;
  createdOn?: string;
  id?: number;
  modifiedBy?: string | null;
  modifiedOn?: string;
}
