/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Doctor } from '../models/doctor';
export interface Hospital {
  createdBy?: string | null;
  createdOn?: string;
  doctors?: Array<Doctor> | null;
  id?: number;
  modifiedBy?: string | null;
  modifiedOn?: string;
  name: string;
}
