/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Doctor } from '../models/doctor';
import { Entity } from '../models/entity';
export type Hospital = Entity & {
'name': string;
'doctors'?: Array<Doctor> | null;
};
