/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Represents a user in the identity system
 */
export interface IdentityUserOfInteger {

  /**
   * Gets or sets the number of failed login attempts for the current user.
   */
  accessFailedCount?: number;

  /**
   * A random value that must change whenever a user is persisted to the store
   */
  concurrencyStamp?: string | null;

  /**
   * Gets or sets the email address for this user.
   */
  email?: string | null;

  /**
   * Gets or sets a flag indicating if a user has confirmed their email address.
   */
  emailConfirmed?: boolean;

  /**
   * Gets or sets the primary key for this user.
   */
  id?: number;

  /**
   * Gets or sets a flag indicating if the user could be locked out.
   */
  lockoutEnabled?: boolean;

  /**
   * Gets or sets the date and time, in UTC, when any user lockout ends.
   */
  lockoutEnd?: string | null;

  /**
   * Gets or sets the normalized email address for this user.
   */
  normalizedEmail?: string | null;

  /**
   * Gets or sets the normalized user name for this user.
   */
  normalizedUserName?: string | null;

  /**
   * Gets or sets a salted and hashed representation of the password for this user.
   */
  passwordHash?: string | null;

  /**
   * Gets or sets a telephone number for the user.
   */
  phoneNumber?: string | null;

  /**
   * Gets or sets a flag indicating if a user has confirmed their telephone address.
   */
  phoneNumberConfirmed?: boolean;

  /**
   * A random value that must change whenever a users credentials change (password changed, login removed)
   */
  securityStamp?: string | null;

  /**
   * Gets or sets a flag indicating if two factor authentication is enabled for this user.
   */
  twoFactorEnabled?: boolean;

  /**
   * Gets or sets the user name for this user.
   */
  userName?: string | null;
}
