/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityModel } from '../models/entity-model';
import { PrescriptionModel } from '../models/prescription-model';
export type PatientModel = EntityModel & {
'userId'?: number;
'firstName'?: string | null;
'lastName'?: string | null;
'fullName'?: string | null;
'prescriptions'?: Array<PrescriptionModel> | null;
};
