/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Appointment } from '../models/appointment';
import { Entity } from '../models/entity';
import { Prescription } from '../models/prescription';
import { User } from '../models/user';
export type Patient = Entity & {
'userId': number;
'user'?: User | null;
'appointments'?: Array<Appointment> | null;
'prescriptions'?: Array<Prescription> | null;
};
