/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Appointment } from '../models/appointment';
import { Entity } from '../models/entity';
import { Patient } from '../models/patient';
import { PrescriptionIntake } from '../models/prescription-intake';
export type Prescription = Entity & {
'name': string;
'dose'?: string | null;
'patientId'?: number;
'patient'?: Patient | null;
'appointmentId'?: number;
'appointment'?: Appointment | null;
'startDate'?: string;
'durationInDays'?: number;
'times'?: Array<string> | null;
'isActive'?: boolean;
'intakes'?: Array<PrescriptionIntake> | null;
};
