/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entity } from '../models/entity';
import { Prescription } from '../models/prescription';
export type PrescriptionIntake = Entity & {
'prescriptionId'?: number;
'prescription'?: Prescription | null;
'scheduledFor'?: string;
'takenAt'?: string | null;
};
