/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Appointment } from '../models/appointment';
import { Entity } from '../models/entity';
import { User } from '../models/user';
export type Prescription = Entity & {
'name': string;
'dose'?: string | null;
'userId'?: number;
'patient'?: User | null;
'appointmentId'?: number;
'appointment'?: Appointment | null;
'startDate'?: string;
'durationInDays'?: number;
'times'?: Array<string> | null;
'isActive'?: boolean;
};
