/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityModel } from '../models/entity-model';
export type PushSubscriptionModel = EntityModel & {
'userId': number;
'endpoint': string;
'p256dh': string;
'auth': string;
};
