/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PushNotificationTestRequest {
  body?: string | null;
  title?: string | null;
  url?: string | null;
  userId?: number | null;
}
