/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppointmentStatus } from '../models/appointment-status';
export interface UpdateAppointmentModel {
  status?: AppointmentStatus;
}
