/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppointmentStatus } from '../models/appointment-status';
import { PrescriptionModel } from '../models/prescription-model';
export interface UpdateAppointmentModel {
  notes?: string | null;
  prescriptions?: Array<PrescriptionModel> | null;
  status?: AppointmentStatus;
}
