/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserModel {
  createdBy?: string | null;
  createdOn?: string;
  firstName?: string | null;
  id?: number;
  lastName?: string | null;
  modifiedBy?: string | null;
  modifiedOn?: string;
}
