/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityModel } from '../models/entity-model';
export type UserModel = EntityModel & {
'firstName'?: string | null;
'lastName'?: string | null;
};
