/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IdentityUserOfInteger } from '../models/identity-user-of-integer';
export type User = IdentityUserOfInteger & {
'firstName': string;
'lastName': string;
'createdBy': string;
'createdOn'?: string;
'modifiedBy': string;
'modifiedOn'?: string;
};
