/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserAndRoles {
  firstName?: string | null;
  id?: number;
  lastName?: string | null;
  roles?: Array<string> | null;
}
