/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  accessFailedCount?: number;
  concurrencyStamp?: string | null;
  createdBy: string;
  createdOn?: string;
  email?: string | null;
  emailConfirmed?: boolean;
  firstName: string;
  id?: number;
  lastName: string;
  lockoutEnabled?: boolean;
  lockoutEnd?: string | null;
  modifiedBy: string;
  modifiedOn?: string;
  normalizedEmail?: string | null;
  normalizedUserName?: string | null;
  passwordHash?: string | null;
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  securityStamp?: string | null;
  twoFactorEnabled?: boolean;
  userName?: string | null;
}
