/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Appointment } from './models/appointment';
export type { AppointmentModel } from './models/appointment-model';
export { AppointmentStatus } from './models/appointment-status';
export type { CreateDoctorModel } from './models/create-doctor-model';
export type { Department } from './models/department';
export type { DepartmentModel } from './models/department-model';
export type { Doctor } from './models/doctor';
export type { DoctorModel } from './models/doctor-model';
export type { Entity } from './models/entity';
export type { EntityModel } from './models/entity-model';
export type { Hospital } from './models/hospital';
export type { HospitalModel } from './models/hospital-model';
export type { IdentityUserOfInteger } from './models/identity-user-of-integer';
export type { LoginRequestModel } from './models/login-request-model';
export type { Prescription } from './models/prescription';
export type { RegisterUserRequestModel } from './models/register-user-request-model';
export type { User } from './models/user';
export type { UserModel } from './models/user-model';
