/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AppointmentModel } from './models/appointment-model';
export { AppointmentStatus } from './models/appointment-status';
export type { ChangeUserPasswordRequestModel } from './models/change-user-password-request-model';
export type { CreateAppointmentModel } from './models/create-appointment-model';
export type { CreateDoctorModel } from './models/create-doctor-model';
export type { DepartmentModel } from './models/department-model';
export type { DoctorModel } from './models/doctor-model';
export type { EntityModel } from './models/entity-model';
export type { HospitalModel } from './models/hospital-model';
export type { LoginRequestModel } from './models/login-request-model';
export type { PatientModel } from './models/patient-model';
export type { PrescriptionIntakeModel } from './models/prescription-intake-model';
export type { PrescriptionModel } from './models/prescription-model';
export type { PushNotificationTestRequest } from './models/push-notification-test-request';
export type { PushSubscriptionModel } from './models/push-subscription-model';
export type { RegisterUserRequestModel } from './models/register-user-request-model';
export type { UpdateAppointmentModel } from './models/update-appointment-model';
export type { UpdateDoctorModel } from './models/update-doctor-model';
export type { UserAndRoles } from './models/user-and-roles';
export type { UserModel } from './models/user-model';
