/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreateDoctorModel } from './models/create-doctor-model';
export type { Department } from './models/department';
export type { DepartmentModel } from './models/department-model';
export type { Doctor } from './models/doctor';
export type { DoctorModel } from './models/doctor-model';
export type { Hospital } from './models/hospital';
export type { HospitalModel } from './models/hospital-model';
export type { LoginRequestModel } from './models/login-request-model';
export type { RegisterUserRequestModel } from './models/register-user-request-model';
export type { User } from './models/user';
export type { UserModel } from './models/user-model';
