/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrescriptionIntakeModel } from '../../models/prescription-intake-model';

export interface PrescriptionIntakeMark$Params {
      body: PrescriptionIntakeModel
}

export function prescriptionIntakeMark(http: HttpClient, rootUrl: string, params: PrescriptionIntakeMark$Params, context?: HttpContext): Observable<StrictHttpResponse<PrescriptionIntakeModel>> {
  const rb = new RequestBuilder(rootUrl, prescriptionIntakeMark.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PrescriptionIntakeModel>;
    })
  );
}

prescriptionIntakeMark.PATH = '/api/PrescriptionIntake/Mark';
