/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrescriptionIntakeModel } from '../../models/prescription-intake-model';

export interface PrescriptionIntakeGetAll$Params {
}

export function prescriptionIntakeGetAll(http: HttpClient, rootUrl: string, params?: PrescriptionIntakeGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PrescriptionIntakeModel>>> {
  const rb = new RequestBuilder(rootUrl, prescriptionIntakeGetAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PrescriptionIntakeModel>>;
    })
  );
}

prescriptionIntakeGetAll.PATH = '/api/PrescriptionIntake';
