/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrescriptionIntakeModel } from '../../models/prescription-intake-model';

export interface PrescriptionIntakeGet$Params {
  id: number;
}

export function prescriptionIntakeGet(http: HttpClient, rootUrl: string, params: PrescriptionIntakeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PrescriptionIntakeModel>> {
  const rb = new RequestBuilder(rootUrl, prescriptionIntakeGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PrescriptionIntakeModel>;
    })
  );
}

prescriptionIntakeGet.PATH = '/api/PrescriptionIntake/{id}';
