/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorModel } from '../../models/doctor-model';

export interface ApiDoctorGet$Json$Params {
}

export function apiDoctorGet$Json(http: HttpClient, rootUrl: string, params?: ApiDoctorGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DoctorModel>>> {
  const rb = new RequestBuilder(rootUrl, apiDoctorGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DoctorModel>>;
    })
  );
}

apiDoctorGet$Json.PATH = '/api/Doctor';
