/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorModel } from '../../models/doctor-model';

export interface ApiDoctorIdGet$Plain$Params {
  id: number;
}

export function apiDoctorIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiDoctorIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DoctorModel>> {
  const rb = new RequestBuilder(rootUrl, apiDoctorIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DoctorModel>;
    })
  );
}

apiDoctorIdGet$Plain.PATH = '/api/Doctor/{id}';
