/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorModel } from '../../models/doctor-model';

export interface ApiDoctorIdGet$Json$Params {
  id: number;
}

export function apiDoctorIdGet$Json(http: HttpClient, rootUrl: string, params: ApiDoctorIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DoctorModel>> {
  const rb = new RequestBuilder(rootUrl, apiDoctorIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DoctorModel>;
    })
  );
}

apiDoctorIdGet$Json.PATH = '/api/Doctor/{id}';
