/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentModel } from '../../models/appointment-model';

export interface DoctorGetAppointmentsForDoctor$Params {
  doctorId?: number;
  month?: number;
}

export function doctorGetAppointmentsForDoctor(http: HttpClient, rootUrl: string, params?: DoctorGetAppointmentsForDoctor$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentModel>>> {
  const rb = new RequestBuilder(rootUrl, doctorGetAppointmentsForDoctor.PATH, 'get');
  if (params) {
    rb.query('doctorId', params.doctorId, {});
    rb.query('month', params.month, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppointmentModel>>;
    })
  );
}

doctorGetAppointmentsForDoctor.PATH = '/api/Doctor/GetAppointmentsForDoctor';
