/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartmentModel } from '../../models/department-model';

export interface ApiDepartmentIdGet$Json$Params {
  id: number;
}

export function apiDepartmentIdGet$Json(http: HttpClient, rootUrl: string, params: ApiDepartmentIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartmentModel>> {
  const rb = new RequestBuilder(rootUrl, apiDepartmentIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DepartmentModel>;
    })
  );
}

apiDepartmentIdGet$Json.PATH = '/api/Department/{id}';
