/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartmentModel } from '../../models/department-model';

export interface DepartmentGetAll$Params {
}

export function departmentGetAll(http: HttpClient, rootUrl: string, params?: DepartmentGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartmentModel>>> {
  const rb = new RequestBuilder(rootUrl, departmentGetAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DepartmentModel>>;
    })
  );
}

departmentGetAll.PATH = '/api/Department';
