/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { homeIndex } from '../fn/home/home-index';
import { HomeIndex$Params } from '../fn/home/home-index';

@Injectable({ providedIn: 'root' })
export class HomeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `homeIndex()` */
  static readonly HomeIndexPath = '/api/Home';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `homeIndex()` instead.
   *
   * This method doesn't expect any request body.
   */
  homeIndex$Response(params?: HomeIndex$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    const obs = homeIndex(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `homeIndex$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  homeIndex(params?: HomeIndex$Params, context?: HttpContext): Observable<Blob> {
    const resp = this.homeIndex$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
