/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientModel } from '../../models/patient-model';

export interface PatientGet$Params {
  id: number;
}

export function patientGet(http: HttpClient, rootUrl: string, params: PatientGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PatientModel>> {
  const rb = new RequestBuilder(rootUrl, patientGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PatientModel>;
    })
  );
}

patientGet.PATH = '/api/Patient/{id}';
