/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrescriptionModel } from '../../models/prescription-model';

export interface PrescriptionGet$Params {
  id: number;
}

export function prescriptionGet(http: HttpClient, rootUrl: string, params: PrescriptionGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PrescriptionModel>> {
  const rb = new RequestBuilder(rootUrl, prescriptionGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PrescriptionModel>;
    })
  );
}

prescriptionGet.PATH = '/api/Prescription/{id}';
