/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrescriptionModel } from '../../models/prescription-model';

export interface PrescriptionGetAll$Params {
}

export function prescriptionGetAll(http: HttpClient, rootUrl: string, params?: PrescriptionGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PrescriptionModel>>> {
  const rb = new RequestBuilder(rootUrl, prescriptionGetAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PrescriptionModel>>;
    })
  );
}

prescriptionGetAll.PATH = '/api/Prescription';
