// <auto-generated />
using System;
using HealthCare.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthCare.Infrastructure.Migrations
{
    [DbContext(typeof(HealthCareDbContext))]
    [Migration("20251013204323_AppointmentNotesProperty")]
    partial class AppointmentNotesProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthCare.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Aesthetic plastic and reconstructive surgery"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Allergology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cardiovascular surgery"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chest surgery"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ear nose and throat"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Endocrinology diabetes and metabolic diseases"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "General surgery"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hematology"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Infections diseases"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Internal medicine"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nephrology"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nutrition and dietetics"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Obstetrics and genecology"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Physiotherapy"
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Radiotherapy"
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "script",
                            CreatedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "script",
                            ModifiedOn = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rheumatology"
                        });
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Times")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Appointment", b =>
                {
                    b.HasOne("HealthCare.Core.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Core.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Doctor", b =>
                {
                    b.HasOne("HealthCare.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Core.Entities.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Hospital");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Patient", b =>
                {
                    b.HasOne("HealthCare.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Prescription", b =>
                {
                    b.HasOne("HealthCare.Core.Entities.Appointment", "Appointment")
                        .WithMany("Prescriptions")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Core.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HealthCare.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HealthCare.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HealthCare.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Appointment", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HealthCare.Core.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
